package com.chf.bbcms.organization.domain;

public enum LeadershipPosition {
    BBC_PRESIDENT,
    BBC_VICE_PRESIDENT,
    BBC_SECRETARY,
    CLASS_PRESIDENT,
    CLASS_VICE_PRESIDENT,
    INTERCESSORY_LEADER,
    EVANGELISM_DISCIPLESHIP_LEADER,
    ACADEMIC_LEADER,
    FINANCIAL_LEADER,
    COMMUNICATION_LEADER,
    DAILY_VERSE_LEADER,
    MIGHTY_MEN_LEADER,
    LADIES_LEADER,
    WELFARE_LEADER,
    ACT_OF_CHRIST_LEADER,
    CHARIS_LEADER,
    DIVINE_SHAKER_LEADER,
    NATIONAL_PRESIDENT,
    NATIONAL_VICE_PRESIDENT_STUDENTS,
    NATIONAL_VICE_PRESIDENT_PROFESSIONALS,
    NATIONAL_SECRETARY_GENERAL,
    NATIONAL_BOT_MEMBER
}
